warn-by-default = true
msrv = "1.70.0"

# Deny certain lints
disallowed-methods = [
    { path = "std::env::set_var", reason = "Use a proper configuration system instead" },
    { path = "std::env::remove_var", reason = "Use a proper configuration system instead" }
]

# Configure complexity thresholds
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
type-complexity-threshold = 250
too-many-lines-threshold = 400
trivial-copy-size-limit = 8

# Allow certain patterns
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-print-in-tests = true
allow-dbg-in-tests = true

# Enforce documentation
missing-docs-in-crate-items = true

# Style preferences
enum-variant-name-threshold = 3
single-char-binding-names-threshold = 4
max-struct-bools = 3
max-fn-params-bools = 3
vec-box-size-threshold = 4096

# Avoid false positives
avoid-breaking-exported-api = true
upper-case-acronyms-aggressive = false