edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
fn_args_layout = "Tall"
merge_derives = true
use_field_init_shorthand = true
force_explicit_abi = true
condense_wildcard_suffixes = false
color = "Auto"
unstable_features = false
normalize_comments = false
normalize_doc_attributes = false
format_code_in_doc_comments = true
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Mixed"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
overflow_delimited_expr = false